-- Add new values to the ActionResult PostgreSQL enum
-- Run this in Supabase SQL Editor BEFORE running prisma generate

ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'REFUS';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'REFUS_ARGU';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'REFUS_CATEGORIQUE';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'RELANCE';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'RAPPEL';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'GERE_PAR_SIEGE';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'FAUX_NUMERO';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'PROJET_A_SUIVRE';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'MAUVAIS_INTERLOCUTEUR';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'MAIL_UNIQUEMENT';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'BARRAGE_SECRETAIRE';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'MAIL_DOC';
ALTER TYPE "ActionResult" ADD VALUE IF NOT EXISTS 'HORS_CIBLE';

-- Verify the enum values
SELECT unnest(enum_range(NULL::"ActionResult")) AS action_result;
