[variables]
NPM_CONFIG_PRODUCTION = "false"
NEXT_TELEMETRY_DISABLED = "1"
NODE_OPTIONS = "--max-old-space-size=4096"

[phases.install]
cmds = ["npm ci --include=dev --no-audit --fund=false"]

[phases.build]
cmds = [
  "npm run build",
  "cp -r .next/static .next/standalone/.next/static",
  "cp -r public .next/standalone/public",
  "rm -rf node_modules",
  "find .next -mindepth 1 -maxdepth 1 ! -name standalone -exec rm -rf {} +"
]

[start]
cmd = "node .next/standalone/server.js"
