-- CreateEnum
CREATE TYPE "OffreTarifStatut" AS ENUM ('ACTIF', 'ARCHIVE');

-- CreateEnum
CREATE TYPE "EngagementStatut" AS ENUM ('BROUILLON', 'ACTIF', 'EXPIRE', 'RENOUVELE', 'RESILIE', 'ARCHIVE');

-- CreateTable
CREATE TABLE "OffreTarif" (
    "id" TEXT NOT NULL,
    "nom" TEXT NOT NULL,
    "fixeMensuel" DECIMAL(10,2) NOT NULL,
    "prixParRdv" DECIMAL(10,2) NOT NULL,
    "description" TEXT,
    "statut" "OffreTarifStatut" NOT NULL DEFAULT 'ACTIF',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OffreTarif_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Engagement" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "offreTarifId" TEXT NOT NULL,
    "fixeOverride" DECIMAL(10,2),
    "rdvOverride" DECIMAL(10,2),
    "dureeMois" INTEGER NOT NULL,
    "debut" TIMESTAMP(3) NOT NULL,
    "fin" TIMESTAMP(3) NOT NULL,
    "statut" "EngagementStatut" NOT NULL DEFAULT 'BROUILLON',
    "penaliteResiliation" TEXT,
    "renouvellement" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Engagement_pkey" PRIMARY KEY ("id")
);

-- AlterTable
ALTER TABLE "BillingClient" ADD COLUMN "clientId" TEXT;

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN "engagementId" TEXT,
ADD COLUMN "periodStart" TIMESTAMP(3),
ADD COLUMN "periodEnd" TIMESTAMP(3),
ADD COLUMN "nbRdvTotal" INTEGER,
ADD COLUMN "montantFixe" DECIMAL(10,2),
ADD COLUMN "montantVariable" DECIMAL(10,2),
ADD COLUMN "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "missionBreakdown" JSONB;

-- CreateIndex
CREATE INDEX "OffreTarif_statut_idx" ON "OffreTarif"("statut");

-- CreateIndex
CREATE INDEX "Engagement_clientId_idx" ON "Engagement"("clientId");

-- CreateIndex
CREATE INDEX "Engagement_offreTarifId_idx" ON "Engagement"("offreTarifId");

-- CreateIndex
CREATE INDEX "Engagement_statut_idx" ON "Engagement"("statut");

-- CreateIndex
CREATE UNIQUE INDEX "BillingClient_clientId_key" ON "BillingClient"("clientId");

-- CreateIndex
CREATE INDEX "BillingClient_clientId_idx" ON "BillingClient"("clientId");

-- CreateIndex
CREATE INDEX "Invoice_engagementId_idx" ON "Invoice"("engagementId");

-- CreateIndex
CREATE INDEX "Invoice_periodStart_idx" ON "Invoice"("periodStart");

-- AddForeignKey
ALTER TABLE "Engagement" ADD CONSTRAINT "Engagement_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Engagement" ADD CONSTRAINT "Engagement_offreTarifId_fkey" FOREIGN KEY ("offreTarifId") REFERENCES "OffreTarif"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "BillingClient" ADD CONSTRAINT "BillingClient_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_engagementId_fkey" FOREIGN KEY ("engagementId") REFERENCES "Engagement"("id") ON DELETE SET NULL ON UPDATE CASCADE;
