import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { successResponse, errorResponse } from "@/lib/api-utils";
import { generateDraftsForPeriod } from "@/lib/billing/engagement-invoice-service";
import { subMonths } from "date-fns";

/**
 * GET/POST /api/billing/cron/month-end
 * Called by a scheduler (e.g. Vercel Cron, cron job) at end of month to generate
 * draft invoices for all active engagements for the previous month.
 * Secured by CRON_SECRET or BILLING_CRON_SECRET in env.
 */
export async function GET(request: NextRequest) {
    return runMonthEnd(request);
}

export async function POST(request: NextRequest) {
    return runMonthEnd(request);
}

async function runMonthEnd(request: NextRequest) {
    const secret = process.env.BILLING_CRON_SECRET || process.env.CRON_SECRET;
    if (secret) {
        const authHeader = request.headers.get("authorization");
        const querySecret = request.nextUrl.searchParams.get("secret");
        const valid = authHeader === `Bearer ${secret}` || querySecret === secret;
        if (!valid) return errorResponse("Unauthorized", 401);
    }

    const now = new Date();
    const lastMonth = subMonths(now, 1);
    const periodYear = lastMonth.getFullYear();
    const periodMonth = lastMonth.getMonth() + 1;

    const manager = await prisma.user.findFirst({
        where: { role: "MANAGER" },
        select: { id: true },
    });
    if (!manager) {
        return errorResponse("Aucun utilisateur MANAGER pour attribuer les factures", 500);
    }

    try {
        const results = await generateDraftsForPeriod(periodYear, periodMonth, manager.id, { isAutoGenerated: true });
        return successResponse({
            message: `${results.length} facture(s) brouillon générée(s) pour ${periodMonth}/${periodYear}`,
            generated: results.length,
            periodYear,
            periodMonth,
            invoices: results.map((r) => ({ invoiceId: r.invoiceId, invoiceNumber: r.invoiceNumber })),
        });
    } catch (err) {
        console.error("Billing month-end cron error:", err);
        return errorResponse(err instanceof Error ? err.message : "Erreur génération", 500);
    }
}
