/**
 * Generate draft invoices from engagements (fixed + RDV count for a period).
 */

import { prisma } from "@/lib/prisma";
import { Decimal } from "@prisma/client/runtime/library";
import { getRdvCountForClient } from "./rdv-count-service";
import { startOfMonth, endOfMonth, addDays } from "date-fns";
import { invoiceService } from "./invoice-service";

const VAT_RATE = 20;

export interface GenerateDraftResult {
    invoiceId: string;
    invoiceNumber: string | null;
    billingClientId: string;
    periodStart: Date;
    periodEnd: Date;
    nbRdvTotal: number;
    montantFixe: number;
    montantVariable: number;
    totalTtc: number;
}

/**
 * Ensure the CRM Client has a BillingClient (create minimal one if missing) and link it.
 */
export async function ensureBillingClientForClient(clientId: string): Promise<string> {
    const existing = await prisma.billingClient.findUnique({
        where: { clientId },
    });
    if (existing) return existing.id;

    const client = await prisma.client.findUnique({
        where: { id: clientId },
    });
    if (!client) throw new Error("Client introuvable");

    const billingClient = await prisma.billingClient.create({
        data: {
            legalName: client.name,
            address: "À renseigner",
            city: "",
            postalCode: "",
            country: "France",
            clientId: client.id,
        },
    });
    return billingClient.id;
}

/**
 * Generate a draft invoice for an engagement and a given month.
 * Uses RDV count for that month, effective fixe + prix_par_rdv from engagement.
 */
export async function generateDraftFromEngagement(
    engagementId: string,
    periodYear: number,
    periodMonth: number,
    userId: string,
    options?: { isAutoGenerated?: boolean }
): Promise<GenerateDraftResult> {
    const periodStart = startOfMonth(new Date(periodYear, periodMonth - 1));
    const periodEnd = endOfMonth(new Date(periodYear, periodMonth - 1));

    const engagement = await prisma.engagement.findUnique({
        where: { id: engagementId },
        include: {
            client: true,
            offreTarif: true,
        },
    });

    if (!engagement) throw new Error("Engagement introuvable");
    if (engagement.statut !== "ACTIF") {
        throw new Error("L'engagement doit être actif pour générer une facture");
    }

    const existing = await prisma.invoice.findFirst({
        where: {
            engagementId,
            periodStart,
            status: { not: "CANCELLED" },
            documentType: "INVOICE",
        },
    });
    if (existing) throw new Error("Une facture existe déjà pour cette période");

    const billingClientId = await ensureBillingClientForClient(engagement.clientId);
    const rdvResult = await getRdvCountForClient(engagement.clientId, periodStart, periodEnd);

    const fixe = Number(engagement.fixeOverride ?? engagement.offreTarif.fixeMensuel);
    const prixRdv = Number(engagement.rdvOverride ?? engagement.offreTarif.prixParRdv);
    const montantFixe = fixe;
    const montantVariable = rdvResult.total * prixRdv;
    const totalHt = montantFixe + montantVariable;
    const totalVat = Math.round(totalHt * (VAT_RATE / 100) * 100) / 100;
    const totalTtc = Math.round((totalHt + totalVat) * 100) / 100;

    const issuer = await prisma.companyIssuer.findFirst();
    if (!issuer) throw new Error("Aucun émetteur configuré (Paramètres facturation)");

    const issueDate = new Date(periodYear, periodMonth - 1, 1);
    const dueDate = addDays(issueDate, issuer.defaultPaymentTermsDays ?? 30);

    const items = [
        {
            description: `Forfait mensuel — ${periodMonth}/${periodYear}`,
            quantity: 1,
            unitPriceHt: montantFixe,
            vatRate: VAT_RATE,
        },
        ...(rdvResult.total > 0
            ? [
                  {
                      description: `Rendez-vous qualifiés — ${rdvResult.total} RDV (${rdvResult.byMission.length} mission(s))`,
                      quantity: rdvResult.total,
                      unitPriceHt: prixRdv,
                      vatRate: VAT_RATE,
                  },
              ]
            : []),
    ];

    const invoiceNumber = await invoiceService.generateInvoiceNumber("INVOICE");

    const invoice = await prisma.invoice.create({
        data: {
            invoiceNumber,
            status: "DRAFT",
            documentType: "INVOICE",
            billingClientId,
            companyIssuerId: issuer.id,
            issueDate,
            dueDate,
            currency: "EUR",
            totalHt: new Decimal(totalHt),
            totalVat: new Decimal(totalVat),
            totalTtc: new Decimal(totalTtc),
            paymentTermsDays: issuer.defaultPaymentTermsDays ?? 30,
            paymentTermsText: `Paiement à ${issuer.defaultPaymentTermsDays ?? 30} jours date de facture`,
            latePenaltyRate: issuer.defaultLatePenaltyRate ?? new Decimal(0),
            earlyPaymentDiscount: issuer.defaultEarlyPaymentDiscount ?? null,
            createdById: userId,
            engagementId,
            periodStart,
            periodEnd,
            nbRdvTotal: rdvResult.total,
            montantFixe: new Decimal(montantFixe),
            montantVariable: new Decimal(montantVariable),
            isAutoGenerated: options?.isAutoGenerated ?? false,
            missionBreakdown: rdvResult.byMission.length > 0 ? rdvResult.byMission : undefined,
            items: {
                create: items.map((item, order) => {
                    const qty = item.quantity;
                    const unit = item.unitPriceHt;
                    const ht = Math.round(qty * unit * 100) / 100;
                    const vat = Math.round(ht * (item.vatRate / 100) * 100) / 100;
                    const ttc = ht + vat;
                    return {
                        description: item.description,
                        quantity: new Decimal(qty),
                        unitPriceHt: new Decimal(unit),
                        vatRate: new Decimal(item.vatRate),
                        totalHt: new Decimal(ht),
                        totalVat: new Decimal(vat),
                        totalTtc: new Decimal(ttc),
                        order,
                    };
                }),
            },
        },
    });

    await prisma.invoiceAuditLog.create({
        data: { invoiceId: invoice.id, action: "CREATED", userId, details: { source: "engagement", engagementId, periodYear, periodMonth } },
    });

    return {
        invoiceId: invoice.id,
        invoiceNumber: invoice.invoiceNumber,
        billingClientId,
        periodStart,
        periodEnd,
        nbRdvTotal: rdvResult.total,
        montantFixe,
        montantVariable,
        totalTtc,
    };
}

/**
 * Generate draft invoices for all clients with an active engagement for the given month.
 */
export async function generateDraftsForPeriod(
    periodYear: number,
    periodMonth: number,
    userId: string,
    options?: { clientId?: string; engagementId?: string; isAutoGenerated?: boolean }
): Promise<GenerateDraftResult[]> {
    const periodStart = startOfMonth(new Date(periodYear, periodMonth - 1));

    const where: { statut: "ACTIF"; clientId?: string; id?: string } = { statut: "ACTIF" };
    if (options?.clientId) where.clientId = options.clientId;
    if (options?.engagementId) where.id = options.engagementId;

    const engagements = await prisma.engagement.findMany({
        where,
        select: { id: true },
    });

    const results: GenerateDraftResult[] = [];
    for (const e of engagements) {
        try {
            const r = await generateDraftFromEngagement(e.id, periodYear, periodMonth, userId, {
                isAutoGenerated: options?.isAutoGenerated,
            });
            results.push(r);
        } catch (err) {
            console.warn(`Skip engagement ${e.id}:`, err);
        }
    }
    return results;
}
