"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { useToast, useConfirm, usePrompt } from "@/components/ui";
import {
    FileCheck,
    Download,
    ArrowLeft,
    Loader2,
    Send,
    Ban,
    FileX2,
    History,
    FileText,
    ExternalLink,
    Building2,
    Calendar,
    CreditCard,
    MapPin,
    Hash,
    Receipt,
    Clock,
    ChevronRight,
    Zap,
    ChevronDown,
    ChevronUp,
} from "lucide-react";
import { Button, Badge, Card, LoadingState } from "@/components/ui";
import { InvoiceItemsTable, InvoiceItem } from "@/components/billing/InvoiceItemsTable";
import { PaymentSection } from "@/components/billing/PaymentSection";
import Link from "next/link";
import { format } from "date-fns";
import { fr } from "date-fns/locale";

interface Invoice {
    id: string;
    invoiceNumber: string | null;
    status: "DRAFT" | "VALIDATED" | "SENT" | "PAID" | "CANCELLED" | "PARTIALLY_PAID";
    documentType: "INVOICE" | "CREDIT_NOTE";
    issueDate: string;
    dueDate: string;
    totalHt: number;
    totalVat: number;
    totalTtc: number;
    currency: string;
    paymentTermsDays: number;
    paymentTermsText: string | null;
    latePenaltyRate: number;
    earlyPaymentDiscount: string | null;
    notes: string | null;
    facturxPdfUrl: string | null;
    cancelledAt: string | null;
    validatedAt: string | null;
    sentAt: string | null;
    paidAt: string | null;
    billingClient: {
        id: string;
        legalName: string;
        address: string;
        city: string;
        postalCode: string;
        siret: string | null;
        vatNumber: string | null;
    };
    companyIssuer: {
        legalName: string;
        address: string;
        city: string;
        postalCode: string;
        siret: string;
        vatNumber: string | null;
        legalForm: string | null;
        capitalSocial: string | null;
        rcsCity: string | null;
        rcsNumber: string | null;
        iban: string | null;
        bic: string | null;
    };
    items: Array<{
        id: string;
        description: string;
        quantity: number;
        unitPriceHt: number;
        vatRate: number;
        totalHt: number;
        totalVat: number;
        totalTtc: number;
    }>;
    payments: Array<{
        id: string;
        amount: number;
        paymentDate: string;
        status: "MATCHED" | "CONFIRMED";
        matchedAt: string;
        confirmedAt: string | null;
        confirmedBy: { name: string } | null;
    }>;
    periodStart?: string | null;
    periodEnd?: string | null;
    nbRdvTotal?: number | null;
    montantFixe?: number | null;
    montantVariable?: number | null;
    isAutoGenerated?: boolean;
    missionBreakdown?: Array<{ missionId: string; missionName: string; rdvCount: number }> | null;
    relatedInvoice: { id: string; invoiceNumber: string | null; status: string } | null;
    creditNotes: Array<{
        id: string;
        invoiceNumber: string | null;
        status: string;
        totalTtc: number;
        createdAt: string;
    }>;
    auditLogs: Array<{
        id: string;
        action: string;
        details: any;
        createdAt: string;
        user: { id: string; name: string; email: string };
    }>;
}

const STATUS_CONFIG: Record<string, { label: string; color: string; bg: string; dot: string }> = {
    DRAFT: { label: "Brouillon", color: "text-slate-600", bg: "bg-slate-100", dot: "bg-slate-400" },
    VALIDATED: { label: "Validée", color: "text-primary-700", bg: "bg-primary-50", dot: "bg-primary-500" },
    SENT: { label: "Envoyée", color: "text-amber-700", bg: "bg-amber-50", dot: "bg-amber-500" },
    PAID: { label: "Payée", color: "text-emerald-700", bg: "bg-emerald-50", dot: "bg-emerald-500" },
    CANCELLED: { label: "Annulée", color: "text-red-700", bg: "bg-red-50", dot: "bg-red-500" },
    PARTIALLY_PAID: { label: "Part. payée", color: "text-amber-700", bg: "bg-amber-50", dot: "bg-amber-500" },
};

const AUDIT_LABELS: Record<string, string> = {
    CREATED: "Facture créée",
    VALIDATED: "Facture validée",
    SENT: "Facture envoyée",
    PAID: "Facture payée",
    CANCELLED: "Facture annulée",
    CREDIT_NOTE_CREATED: "Avoir créé",
    CREDIT_NOTE_ISSUED: "Avoir émis",
    PDP_SUBMISSION_SIMULATED: "Soumission PDP simulée",
};

export default function InvoiceDetailPage({ params }: { params: Promise<{ id: string }> }) {
    const { success, error: showError } = useToast();
    const confirm = useConfirm();
    const prompt = usePrompt();
    const router = useRouter();
    const [invoice, setInvoice] = useState<Invoice | null>(null);
    const [isLoading, setIsLoading] = useState(true);
    const [isValidating, setIsValidating] = useState(false);
    const [isSending, setIsSending] = useState(false);
    const [isCancelling, setIsCancelling] = useState(false);
    const [isCreatingCreditNote, setIsCreatingCreditNote] = useState(false);
    const [invoiceId, setInvoiceId] = useState<string>("");
    const [showMissionBreakdown, setShowMissionBreakdown] = useState(false);

    useEffect(() => {
        params.then((p) => {
            setInvoiceId(p.id);
            fetchInvoice(p.id);
        });
    }, [params]);

    const fetchInvoice = async (id: string) => {
        setIsLoading(true);
        try {
            const res = await fetch(`/api/billing/invoices/${id}`);
            const json = await res.json();
            if (json.success) {
                setInvoice(json.data);
            } else {
                showError("Erreur", json.error);
                router.push("/manager/billing/invoices");
            }
        } catch (err) {
            showError("Erreur", "Impossible de charger la facture");
            router.push("/manager/billing/invoices");
        } finally {
            setIsLoading(false);
        }
    };

    const handleValidate = async () => {
        if (!(await confirm({ title: "Valider cette facture ?", message: "Un numéro sera attribué et un PDF Factur-X sera généré.", confirmText: "Valider" }))) return;
        setIsValidating(true);
        try {
            const res = await fetch(`/api/billing/invoices/${invoiceId}/validate`, { method: "POST" });
            const json = await res.json();
            if (json.success) {
                success("Facture validée", "PDF Factur-X EN16931 généré");
                fetchInvoice(invoiceId);
            } else showError("Erreur", json.error);
        } catch { showError("Erreur", "Impossible de valider"); }
        finally { setIsValidating(false); }
    };

    const handleSend = async () => {
        if (!(await confirm({ title: "Marquer comme envoyée ?", confirmText: "Marquer envoyée" }))) return;
        setIsSending(true);
        try {
            const res = await fetch(`/api/billing/invoices/${invoiceId}/send`, { method: "POST" });
            const json = await res.json();
            if (json.success) { success("Envoyée", "Facture marquée comme envoyée"); fetchInvoice(invoiceId); }
            else showError("Erreur", json.error);
        } catch { showError("Erreur", "Impossible d'envoyer"); }
        finally { setIsSending(false); }
    };

    const handleCancel = async () => {
        const reason = await prompt({ title: "Annuler la facture ?", label: "Raison de l'annulation (optionnel)", variant: "danger", confirmText: "Annuler la facture", cancelText: "Retour" });
        if (reason === null) return;
        setIsCancelling(true);
        try {
            const res = await fetch(`/api/billing/invoices/${invoiceId}/cancel`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ reason }),
            });
            const json = await res.json();
            if (json.success) { success("Annulée", "La facture a été annulée"); fetchInvoice(invoiceId); }
            else showError("Erreur", json.error);
        } catch { showError("Erreur", "Impossible d'annuler"); }
        finally { setIsCancelling(false); }
    };

    const handleCreateCreditNote = async () => {
        if (!(await confirm({ title: "Créer un avoir pour cette facture ?", confirmText: "Créer l'avoir" }))) return;
        setIsCreatingCreditNote(true);
        try {
            const res = await fetch(`/api/billing/invoices/${invoiceId}/credit-note`, { method: "POST" });
            const json = await res.json();
            if (json.success) { success("Avoir créé", "Avoir créé en brouillon"); router.push(`/manager/billing/invoices/${json.data.id}`); }
            else showError("Erreur", json.error);
        } catch { showError("Erreur", "Impossible de créer l'avoir"); }
        finally { setIsCreatingCreditNote(false); }
    };

    const formatCurrency = (amount: number) =>
        new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(amount);

    if (isLoading) {
        return <LoadingState message="Chargement de la facture..." />;
    }

    if (!invoice) return null;

    const isCredit = invoice.documentType === "CREDIT_NOTE";
    const docLabel = isCredit ? "Avoir" : "Facture";
    const sc = STATUS_CONFIG[invoice.status] || STATUS_CONFIG.DRAFT;
    const items: InvoiceItem[] = invoice.items.map((item) => ({
        id: item.id,
        description: item.description,
        quantity: Number(item.quantity),
        unitPriceHt: Number(item.unitPriceHt),
        vatRate: Number(item.vatRate),
        totalHt: Number(item.totalHt),
        totalVat: Number(item.totalVat),
        totalTtc: Number(item.totalTtc),
    }));

    return (
        <div className="space-y-6 max-w-[1200px] mx-auto">
            {/* Breadcrumb + Actions */}
            <div className="flex items-start justify-between gap-4">
                <div>
                    <Link
                        href="/manager/billing/invoices"
                        className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-700 transition-colors mb-3"
                    >
                        <ArrowLeft className="w-4 h-4" />
                        Factures
                    </Link>
                    <div className="flex items-center gap-3">
                        <h1 className="text-2xl font-bold text-slate-900">
                            {invoice.invoiceNumber || "Brouillon"}
                        </h1>
                        {isCredit && (
                            <span className="px-2.5 py-1 rounded-lg bg-red-50 text-red-700 text-xs font-semibold border border-red-200">
                                AVOIR
                            </span>
                        )}
                        <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold ${sc.bg} ${sc.color}`}>
                            <span className={`w-1.5 h-1.5 rounded-full ${sc.dot}`} />
                            {sc.label}
                        </span>
                        {invoice.isAutoGenerated && (
                            <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium bg-slate-100 text-slate-600">
                                <Zap className="w-3 h-3" />
                                Auto-générée
                            </span>
                        )}
                    </div>
                    <p className="text-sm text-slate-500 mt-1">
                        {docLabel} - {invoice.billingClient.legalName}
                        {invoice.periodStart && (
                            <span className="ml-2">
                                · Période {format(new Date(invoice.periodStart), "MMMM yyyy", { locale: fr })}
                            </span>
                        )}
                    </p>
                </div>

                <div className="flex items-center gap-2 flex-shrink-0 flex-wrap justify-end">
                    {invoice.facturxPdfUrl && (
                        <Button variant="secondary" onClick={() => window.open(`/api/billing/invoices/${invoiceId}/pdf`, "_blank")}>
                            <Download className="w-4 h-4 mr-2" />
                            PDF
                        </Button>
                    )}
                    {invoice.status === "DRAFT" && (
                        <Button onClick={handleValidate} disabled={isValidating}>
                            {isValidating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <FileCheck className="w-4 h-4 mr-2" />}
                            Valider
                        </Button>
                    )}
                    {invoice.status === "VALIDATED" && (
                        <Button onClick={handleSend} disabled={isSending}>
                            {isSending ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Send className="w-4 h-4 mr-2" />}
                            Marquer envoyée
                        </Button>
                    )}
                    {["VALIDATED", "SENT"].includes(invoice.status) && (
                        <Button variant="ghost" onClick={handleCancel} disabled={isCancelling}>
                            {isCancelling ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Ban className="w-4 h-4 mr-2" />}
                            Annuler
                        </Button>
                    )}
                    {!isCredit && ["VALIDATED", "SENT", "PAID"].includes(invoice.status) && (
                        <Button variant="ghost" onClick={handleCreateCreditNote} disabled={isCreatingCreditNote}>
                            {isCreatingCreditNote ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <FileX2 className="w-4 h-4 mr-2" />}
                            Avoir
                        </Button>
                    )}
                </div>
            </div>

            {/* Cancelled banner */}
            {invoice.status === "CANCELLED" && (
                <div className="rounded-xl border border-red-200 bg-red-50 p-4 flex items-center gap-3">
                    <div className="w-9 h-9 rounded-full bg-red-100 flex items-center justify-center flex-shrink-0">
                        <Ban className="w-4 h-4 text-red-600" />
                    </div>
                    <div>
                        <p className="font-medium text-red-900">
                            {docLabel} annulé{isCredit ? "" : "e"}
                            {invoice.cancelledAt && ` le ${format(new Date(invoice.cancelledAt), "dd/MM/yyyy", { locale: fr })}`}
                        </p>
                    </div>
                </div>
            )}

            {/* Credit note ref */}
            {isCredit && invoice.relatedInvoice && (
                <Link
                    href={`/manager/billing/invoices/${invoice.relatedInvoice.id}`}
                    className="flex items-center justify-between rounded-xl border border-amber-200 bg-amber-50 p-4 hover:shadow-md transition-shadow group"
                >
                    <div className="flex items-center gap-3">
                        <FileText className="w-5 h-5 text-amber-600" />
                        <span className="text-amber-900">
                            Avoir relatif à <strong>{invoice.relatedInvoice.invoiceNumber}</strong>
                        </span>
                    </div>
                    <ChevronRight className="w-4 h-4 text-amber-400 group-hover:translate-x-1 transition-transform" />
                </Link>
            )}

            {/* Main content */}
            <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                {/* Left: Main content */}
                <div className="lg:col-span-8 space-y-6">
                    {/* Parties */}
                    <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden">
                        <div className="grid grid-cols-2 divide-x divide-slate-100">
                            {/* Issuer */}
                            <div className="p-6">
                                <div className="flex items-center gap-2 mb-3">
                                    <div className="w-7 h-7 rounded-lg bg-primary-100 flex items-center justify-center">
                                        <Building2 className="w-3.5 h-3.5 text-primary-600" />
                                    </div>
                                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Émetteur</span>
                                </div>
                                <h4 className="font-semibold text-slate-900">
                                    {invoice.companyIssuer.legalName}
                                    {invoice.companyIssuer.legalForm && <span className="font-normal text-slate-500"> {invoice.companyIssuer.legalForm}</span>}
                                </h4>
                                <div className="mt-2 text-sm text-slate-600 space-y-0.5">
                                    <p>{invoice.companyIssuer.address}</p>
                                    <p>{invoice.companyIssuer.postalCode} {invoice.companyIssuer.city}</p>
                                    <p className="font-mono text-xs text-slate-500 mt-1">SIRET {invoice.companyIssuer.siret}</p>
                                    {invoice.companyIssuer.vatNumber && (
                                        <p className="font-mono text-xs text-slate-500">TVA {invoice.companyIssuer.vatNumber}</p>
                                    )}
                                </div>
                            </div>
                            {/* Client */}
                            <div className="p-6">
                                <div className="flex items-center gap-2 mb-3">
                                    <div className="w-7 h-7 rounded-lg bg-accent-100 flex items-center justify-center">
                                        <Building2 className="w-3.5 h-3.5 text-accent-600" />
                                    </div>
                                    <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Client</span>
                                </div>
                                <h4 className="font-semibold text-slate-900">{invoice.billingClient.legalName}</h4>
                                <div className="mt-2 text-sm text-slate-600 space-y-0.5">
                                    <p>{invoice.billingClient.address}</p>
                                    <p>{invoice.billingClient.postalCode} {invoice.billingClient.city}</p>
                                    {invoice.billingClient.siret && <p className="font-mono text-xs text-slate-500 mt-1">SIRET {invoice.billingClient.siret}</p>}
                                    {invoice.billingClient.vatNumber && <p className="font-mono text-xs text-slate-500">TVA {invoice.billingClient.vatNumber}</p>}
                                </div>
                            </div>
                        </div>
                        {/* Date bar */}
                        <div className="border-t border-slate-100 bg-slate-50/50 px-6 py-3 flex flex-wrap items-center gap-6 text-sm">
                            {invoice.periodStart && invoice.periodEnd && (
                                <div className="flex items-center gap-2 text-slate-600">
                                    <Calendar className="w-4 h-4 text-slate-400" />
                                    <span>Période: <strong className="text-slate-900">{format(new Date(invoice.periodStart), "dd MMM", { locale: fr })} → {format(new Date(invoice.periodEnd), "dd MMM yyyy", { locale: fr })}</strong></span>
                                </div>
                            )}
                            <div className="flex items-center gap-2 text-slate-600">
                                <Calendar className="w-4 h-4 text-slate-400" />
                                <span>Émission: <strong className="text-slate-900">{format(new Date(invoice.issueDate), "dd MMM yyyy", { locale: fr })}</strong></span>
                            </div>
                            <div className="flex items-center gap-2 text-slate-600">
                                <Clock className="w-4 h-4 text-slate-400" />
                                <span>Échéance: <strong className="text-slate-900">{format(new Date(invoice.dueDate), "dd MMM yyyy", { locale: fr })}</strong></span>
                            </div>
                        </div>
                    </div>

                    {/* Items */}
                    <div className="rounded-2xl border border-slate-200 bg-white p-6">
                        <h2 className="text-lg font-semibold text-slate-900 mb-5">Articles</h2>
                        <InvoiceItemsTable items={items} onChange={() => {}} readOnly={invoice.status !== "DRAFT"} />
                        {invoice.nbRdvTotal != null && invoice.nbRdvTotal > 0 && (invoice.missionBreakdown?.length ?? 0) > 0 && (
                            <div className="mt-4 pt-4 border-t border-slate-100">
                                <button
                                    type="button"
                                    onClick={() => setShowMissionBreakdown((v) => !v)}
                                    className="flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-primary-600"
                                >
                                    {showMissionBreakdown ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                                    Détail par mission ({(invoice.missionBreakdown as Array<{ missionName: string; rdvCount: number }>)?.length ?? 0} missions)
                                </button>
                                {showMissionBreakdown && invoice.missionBreakdown && (
                                    <div className="mt-3 rounded-lg border border-slate-200 overflow-hidden">
                                        {(invoice.missionBreakdown as Array<{ missionId: string; missionName: string; rdvCount: number }>).map((m) => (
                                            <div
                                                key={m.missionId}
                                                className="flex items-center justify-between px-4 py-3 bg-slate-50/50 even:bg-white border-b border-slate-100 last:border-0"
                                            >
                                                <span className="text-sm font-medium text-slate-900">{m.missionName}</span>
                                                <span className="text-sm text-slate-600">{m.rdvCount} RDV{m.rdvCount !== 1 ? "s" : ""}</span>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>
                        )}
                    </div>

                    {/* Credit Notes */}
                    {invoice.creditNotes?.length > 0 && (
                        <div className="rounded-2xl border border-slate-200 bg-white p-6">
                            <h2 className="text-lg font-semibold text-slate-900 mb-4">Avoirs liés</h2>
                            <div className="space-y-2">
                                {invoice.creditNotes.map((cn) => (
                                    <Link
                                        key={cn.id}
                                        href={`/manager/billing/invoices/${cn.id}`}
                                        className="flex items-center justify-between p-4 rounded-xl bg-slate-50 hover:bg-primary-50/50 transition-all duration-150 group"
                                    >
                                        <div className="flex items-center gap-3">
                                            <div className="w-9 h-9 rounded-lg bg-red-50 flex items-center justify-center">
                                                <FileX2 className="w-4 h-4 text-red-500" />
                                            </div>
                                            <div>
                                                <span className="font-medium text-slate-900 group-hover:text-primary-700 transition-colors">
                                                    {cn.invoiceNumber || "Brouillon"}
                                                </span>
                                                <p className="text-xs text-slate-500">{format(new Date(cn.createdAt), "dd/MM/yyyy", { locale: fr })}</p>
                                            </div>
                                        </div>
                                        <div className="flex items-center gap-3">
                                            <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${STATUS_CONFIG[cn.status]?.bg} ${STATUS_CONFIG[cn.status]?.color}`}>
                                                {STATUS_CONFIG[cn.status]?.label}
                                            </span>
                                            <span className="font-semibold text-red-600 tabular-nums">-{formatCurrency(Number(cn.totalTtc))}</span>
                                            <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-primary-400 group-hover:translate-x-0.5 transition-all" />
                                        </div>
                                    </Link>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Audit Trail */}
                    {invoice.auditLogs?.length > 0 && (
                        <div className="rounded-2xl border border-slate-200 bg-white p-6">
                            <h2 className="text-lg font-semibold text-slate-900 mb-5 flex items-center gap-2">
                                <History className="w-5 h-5 text-slate-400" />
                                Historique
                            </h2>
                            <div className="relative">
                                {/* Timeline line */}
                                <div className="absolute left-[18px] top-2 bottom-2 w-px bg-slate-200" />
                                <div className="space-y-5">
                                    {invoice.auditLogs.map((log, idx) => (
                                        <div key={log.id} className="flex items-start gap-4 relative">
                                            <div className={`w-[38px] h-[38px] rounded-full border-2 bg-white flex items-center justify-center flex-shrink-0 z-10 ${
                                                idx === 0 ? "border-primary-400" : "border-slate-200"
                                            }`}>
                                                <div className={`w-2.5 h-2.5 rounded-full ${idx === 0 ? "bg-primary-500" : "bg-slate-300"}`} />
                                            </div>
                                            <div className="flex-1 pb-1">
                                                <p className="text-sm font-medium text-slate-900">
                                                    {AUDIT_LABELS[log.action] || log.action}
                                                </p>
                                                <p className="text-xs text-slate-500 mt-0.5">
                                                    par {log.user.name} - {format(new Date(log.createdAt), "dd/MM/yyyy HH:mm", { locale: fr })}
                                                </p>
                                                {log.details?.reason && (
                                                    <p className="text-xs text-slate-400 mt-1 italic">&quot;{log.details.reason}&quot;</p>
                                                )}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* Right sidebar */}
                <div className="lg:col-span-4 space-y-6">
                    {/* Totals Card */}
                    <div className="rounded-2xl border border-slate-200 bg-white p-6">
                        <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">Montants</h3>
                        <div className="space-y-3">
                            <div className="flex justify-between text-sm">
                                <span className="text-slate-500">Total HT</span>
                                <span className="font-medium text-slate-700 tabular-nums">{formatCurrency(Number(invoice.totalHt))}</span>
                            </div>
                            <div className="flex justify-between text-sm">
                                <span className="text-slate-500">TVA</span>
                                <span className="font-medium text-slate-700 tabular-nums">{formatCurrency(Number(invoice.totalVat))}</span>
                            </div>
                            <div className="h-px bg-slate-200" />
                            <div className="flex justify-between items-center">
                                <span className="font-bold text-slate-900">Total TTC</span>
                                <span className={`text-2xl font-bold tabular-nums ${isCredit ? "text-red-600" : "text-primary-600"}`}>
                                    {isCredit ? "-" : ""}{formatCurrency(Number(invoice.totalTtc))}
                                </span>
                            </div>
                        </div>
                    </div>

                    {/* Bank details */}
                    {invoice.companyIssuer.iban && (
                        <div className="rounded-2xl border border-slate-200 bg-white p-6">
                            <div className="flex items-center gap-2 mb-3">
                                <CreditCard className="w-4 h-4 text-slate-400" />
                                <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Virement</h3>
                            </div>
                            <div className="space-y-2 text-sm">
                                <div>
                                    <p className="text-xs text-slate-400 mb-0.5">IBAN</p>
                                    <p className="font-mono text-xs text-slate-700 bg-slate-50 rounded-lg px-3 py-2 break-all">{invoice.companyIssuer.iban}</p>
                                </div>
                                {invoice.companyIssuer.bic && (
                                    <div>
                                        <p className="text-xs text-slate-400 mb-0.5">BIC</p>
                                        <p className="font-mono text-xs text-slate-700 bg-slate-50 rounded-lg px-3 py-2">{invoice.companyIssuer.bic}</p>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}

                    {/* Conditions */}
                    <div className="rounded-2xl border border-slate-200 bg-white p-6">
                        <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-3">Conditions</h3>
                        <p className="text-sm text-slate-700">
                            {invoice.paymentTermsText || `Paiement à ${invoice.paymentTermsDays || 30} jours`}
                        </p>
                        {invoice.notes && (
                            <div className="mt-3 pt-3 border-t border-slate-100">
                                <p className="text-xs text-slate-400 mb-1">Notes</p>
                                <p className="text-sm text-slate-600">{invoice.notes}</p>
                            </div>
                        )}
                    </div>

                    {/* Payment */}
                    {!isCredit && (
                        <div className="rounded-2xl border border-slate-200 bg-white p-6">
                            <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider mb-4">Paiement</h3>
                            <PaymentSection
                                invoiceId={invoiceId}
                                payments={invoice.payments}
                                invoiceStatus={invoice.status}
                                onPaymentUpdate={() => fetchInvoice(invoiceId)}
                            />
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
